version: "2"

run:
  timeout: 5m
  go: '1.24'

linters:
  enable:
    - misspell
    - revive
  disable:
    - unused
    - godot
    - godox
    - err113
    - wrapcheck
    - exhaustruct
    - ireturn
    - varnamelen
    - tagliatelle
    - nlreturn
    - wsl
    - testpackage
    - paralleltest
    - tparallel
    - gochecknoglobals
    - gochecknoinits
    - forcetypeassert
    - interfacebloat
    - maintidx
    - nestif
    - nonamedreturns
    - noctx
    - contextcheck
    - errorlint
    - exhaustive
    - forbidigo
    - perfsprint
    - mnd
    - dupl

  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
    cyclop:
      max-complexity: 100
    goconst:
      min-len: 2
      min-occurrences: 3
    misspell:
      locale: US
    funlen:
      lines: 500
      statements: 200
    revive:
      rules:
        - name: package-comments
          disabled: true
        - name: empty-block
          disabled: true
        - name: unused-parameter
          disabled: true
        - name: redefines-builtin-id
          disabled: true
    gocognit:
      min-complexity: 200
    errcheck:
      check-blank: false
      check-type-assertions: false

  exclusions:
    rules:
      # Disable errcheck for test files
      - path: _test\.go
        linters:
          - errcheck
      # Disable errcheck for write operations
      - text: "Error return value of.*Write.* is not checked"
        linters:
          - errcheck
      # Ignore unused test mocks and helpers
      - path: _test\.go
        text: "(type|func).*(is unused)"
        linters:
          - unused
      # Ignore unused msgPool (future optimization)
      - path: dns/server\.go
        text: "var msgPool is unused"
        linters:
          - unused
      # Ignore unused prepared statement fields (future use)
      - path: storage/sqlite\.go
        text: "field (stmtGetRecentQueries|stmtGetStatistics) is unused"
        linters:
          - unused
      # Ignore blank identifier assignments in tests
      - path: _test\.go
        text: "S1005:"
        linters:
          - staticcheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
