run:
  timeout: 5m

linters:
  enable-all: true
  disable:
    # Deprecated linters
    - exhaustivestruct
    - golint
    - interfacer
    - maligned
    - scopelint
    - structcheck
    - varcheck
    - deadcode
    - ifshort
    - nosnakecase

    # Overly strict style/formatting linters
    - godot              # Comments must end in period
    - wsl                # Whitespace linting too strict
    - gofumpt            # Stricter gofmt
    - gci                # Import order too strict
    - varnamelen         # Variable name length
    - tagliatelle        # Struct tag naming
    - depguard           # Import restrictions
    - mnd                # Magic number detection
    - perfsprint         # fmt.Errorf vs errors.New
    - forcetypeassert    # Type assertion checking
    - gocritic           # Too many opinionated rules

    # Test-related linters that are too strict
    - nonamedreturns
    - exhaustruct
    - gochecknoinits
    - gochecknoglobals
    - godox
    - testpackage
    - goerr113
    - wrapcheck
    - nlreturn
    - tparallel
    - paralleltest
    - intrange           # Go 1.22+ range syntax
    - usetesting         # Test-specific improvements

    # Field alignment - useful but creates noise
    - fieldalignment

    # Other noisy linters
    - stylecheck   # Style recommendations
    - unused       # Unused code detection (can be noisy)
    - shadow       # Variable shadowing

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: glory-hole
  govet:
    enable:
      - atomic
      - bools
      - buildtag
      - copylocks
      - errorsas
      - httpresponse
      - loopclosure
      - lostcancel
      - nilfunc
      - printf
      - shift
      - stdmethods
      - structtag
      - tests
      - unmarshal
      - unreachable
      - unsafeptr
      - unusedresult
  cyclop:
    max-complexity: 30
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
  funlen:
    lines: 150
    statements: 75
  errorlint:
    errorf: true
  revive:
    rules:
      - name: package-comments
        disabled: true
      - name: empty-block
        disabled: true
      - name: unused-parameter
        disabled: true
      - name: redefines-builtin-id
        disabled: true
  gosec:
    excludes:
      - G304  # Potential file inclusion via variable
      - G306  # Poor file permissions

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
