run:
  timeout: 5m
  go: '1.24'

linters:
  enable:
    - misspell
    - revive
  disable:
    - staticcheck
    - gosimple
    - goconst
    - godot
    - godox
    - err113
    - wrapcheck
    - exhaustruct
    - ireturn
    - varnamelen
    - tagliatelle
    - nlreturn
    - wsl
    - testpackage
    - paralleltest
    - tparallel
    - gochecknoglobals
    - gochecknoinits
    - forcetypeassert
    - interfacebloat
    - maintidx
    - nestif
    - nonamedreturns
    - noctx
    - contextcheck
    - errorlint
    - exhaustive
    - forbidigo
    - perfsprint
    - mnd
    - dupl
    - unused

linters-settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
        - shadow
        - unusedwrite
    cyclop:
      max-complexity: 100
    goconst:
      min-len: 2
      min-occurrences: 3
    misspell:
      locale: US
    funlen:
      lines: 500
      statements: 200
    revive:
      rules:
        - name: package-comments
          disabled: true
        - name: empty-block
          disabled: true
        - name: unused-parameter
          disabled: true
        - name: redefines-builtin-id
          disabled: true
    gocognit:
      min-complexity: 200
    errcheck:
      check-blank: false
      check-type-assertions: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    # Disable errcheck for test files
    - path: _test\.go
      linters:
        - errcheck
    # Disable errcheck for write operations
    - text: "Error return value of.*Write.* is not checked"
      linters:
        - errcheck
    # Ignore unused types in config (for deprecation)
    - path: config\.go
      text: "is unused"
      linters:
        - unused
    # Ignore blank identifier assignments in tests
    - path: _test\.go
      text: "S1005:"
      linters:
        - staticcheck
