run:
  timeout: 5m

linters:
  enable-all: true
  disable:
    # Deprecated linters
    - exhaustivestruct
    - golint
    - interfacer
    - maligned
    - scopelint
    - structcheck
    - varcheck
    - deadcode
    - ifshort
    - nosnakecase

    # Overly strict style/formatting linters
    - godot              # Comments must end in period
    - wsl                # Whitespace linting too strict
    - gofumpt            # Stricter gofmt
    - gci                # Import order too strict
    - varnamelen         # Variable name length
    - tagliatelle        # Struct tag naming
    - depguard           # Import restrictions
    - mnd                # Magic number detection
    - perfsprint         # fmt.Errorf vs errors.New
    - forcetypeassert    # Type assertion checking
    - gocritic           # Too many opinionated rules

    # Test-related linters that are too strict
    - nonamedreturns
    - exhaustruct
    - gochecknoinits
    - gochecknoglobals
    - godox
    - testpackage
    - goerr113
    - wrapcheck
    - nlreturn
    - tparallel
    - paralleltest
    - intrange           # Go 1.22+ range syntax
    - usetesting         # Test-specific improvements

    # Other noisy linters
    - stylecheck   # Style recommendations
    - errchkjson   # JSON marshal error checking
    - contextcheck # Context propagation
    - unused       # Unused code detection
    - gocyclo      # Cyclomatic complexity
    - errorlint    # Error wrapping checks
    - exhaustive   # Exhaustive switch cases
    - forbidigo    # Forbidden identifiers
    - ireturn      # Accept interfaces, return structs
    - interfacebloat # Interface method count
    - nestif       # Nested if complexity
    - mirror       # Allocation optimizations
    - maintidx     # Maintainability index
    - lll          # Line length limit
    - thelper      # Test helper function checks
    - staticcheck  # Static analysis (too strict)
    - sqlclosecheck # SQL resource closing
    - rowserrcheck # SQL rows.Err checking
    - predeclared  # Predeclared identifier naming
    - noctx        # HTTP calls without context
    - usestdlibvars # Stdlib constant usage
    - unparam      # Unused function parameters
    - whitespace   # Whitespace linting

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: glory-hole
  govet:
    enable:
      - atomic
      - bools
      - buildtag
      - copylocks
      - errorsas
      - httpresponse
      - loopclosure
      - lostcancel
      - nilfunc
      - printf
      - shift
      - stdmethods
      - structtag
      - tests
      - unmarshal
      - unreachable
      - unsafeptr
      - unusedresult
  cyclop:
    max-complexity: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
  funlen:
    lines: 500
    statements: 200
  revive:
    rules:
      - name: package-comments
        disabled: true
      - name: empty-block
        disabled: true
      - name: unused-parameter
        disabled: true
      - name: redefines-builtin-id
        disabled: true
  gosec:
    excludes:
      - G104  # Errors unhandled - covered by errcheck
      - G112  # Potential Slowloris Attack
      - G115  # Integer overflow conversion
      - G302  # File permissions
      - G304  # Potential file inclusion via variable
      - G306  # Poor file permissions
  gocognit:
    min-complexity: 200  # Allow high complexity for now

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    # Disable errcheck for test files - defer Close() errors are acceptable
    - path: _test\.go
      linters:
        - errcheck
    # Disable errcheck for write operations - they're logged elsewhere
    - text: "Error return value of.*Write.* is not checked"
      linters:
        - errcheck
