package unbound

import (
	"bytes"
	"fmt"
	"os"
	"text/template"
)

// confTemplate renders a full unbound.conf from an UnboundServerConfig.
var confTemplate = template.Must(template.New("unbound.conf").Funcs(template.FuncMap{
	"yesno": func(b bool) string {
		if b {
			return "yes"
		}
		return "no"
	},
}).Parse(unboundConfTmpl))

const unboundConfTmpl = `# Glory-Hole managed unbound.conf
# This file is generated by the Unbound config model.
# Manual edits will be overwritten on next save.

server:
    # Process
    do-daemonize: no
    username: ""
    chroot: ""
    directory: "/etc/unbound"
    logfile: ""
    pidfile: ""

    # Network
    interface: {{ .Server.Interface }}
    port: {{ .Server.Port }}
    do-ip4: yes
    do-udp: yes
    do-tcp: yes
    do-ip6: no
    prefer-ip6: no

    # Access control
{{- range .Server.AccessControl }}
    access-control: {{ .Netblock }} {{ .Action }}
{{- end }}

    # DNSSEC
    module-config: "{{ .Server.ModuleConfig }}"
{{- if .Server.AutoTrustAnchor }}
    auto-trust-anchor-file: {{ .Server.AutoTrustAnchor }}
{{- end }}
    harden-glue: {{ yesno .Server.HardenGlue }}
    harden-dnssec-stripped: {{ yesno .Server.HardenDNSSEC }}
    harden-below-nxdomain: {{ yesno .Server.HardenBelowNX }}
    harden-algo-downgrade: {{ yesno .Server.HardenAlgoDown }}
    qname-minimisation: {{ yesno .Server.QnameMin }}
    aggressive-nsec: {{ yesno .Server.AggressiveNSEC }}
    val-clean-additional: yes
    val-permissive-mode: no
    ede: yes
    ede-serve-expired: yes
{{- range .Server.DomainInsecure }}
    domain-insecure: "{{ . }}"
{{- end }}

    # Privacy
    use-caps-for-id: no
    rrset-roundrobin: yes
    hide-identity: {{ yesno .Server.HideIdentity }}
    hide-version: {{ yesno .Server.HideVersion }}
    minimal-responses: {{ yesno .Server.MinimalResponses }}

    # Private addresses
{{- range .Server.PrivateAddress }}
    private-address: {{ . }}
{{- end }}

    # Cache
    key-cache-size: {{ .Server.KeyCacheSize }}
    msg-cache-size: {{ .Server.MsgCacheSize }}
    rrset-cache-size: {{ .Server.RRSetCacheSize }}
    cache-min-ttl: {{ .Server.CacheMinTTL }}
    cache-max-negative-ttl: {{ .Server.CacheMaxNegTTL }}
{{- if gt .Server.CacheMaxTTL 0 }}
    cache-max-ttl: {{ .Server.CacheMaxTTL }}
{{- end }}

    # Prefetch
    prefetch: {{ yesno .Server.Prefetch }}
    prefetch-key: {{ yesno .Server.PrefetchKey }}

    # Serve stale
    serve-expired: {{ yesno .Server.ServeExpired }}
    serve-expired-ttl: {{ .Server.ServeExpiredTTL }}
{{- if gt .Server.ServeExpiredClientTimeout 0 }}
    serve-expired-client-timeout: {{ .Server.ServeExpiredClientTimeout }}
{{- end }}

    # Performance
    num-threads: {{ .Server.NumThreads }}
{{- if gt .Server.EDNSBufferSize 0 }}
    edns-buffer-size: {{ .Server.EDNSBufferSize }}
{{- end }}
    so-reuseport: {{ yesno .Server.SoReusePort }}
{{- if gt .Server.OutgoingRange 0 }}
    outgoing-range: {{ .Server.OutgoingRange }}
{{- end }}
{{- if gt .Server.NumQueriesPerThread 0 }}
    num-queries-per-thread: {{ .Server.NumQueriesPerThread }}
{{- end }}
    target-fetch-policy: "3 2 1 0 0"
    so-sndbuf: 4m
    so-rcvbuf: 4m
    jostle-timeout: 200

    # Logging
    verbosity: {{ .Server.Verbosity }}
    log-queries: {{ yesno .Server.LogQueries }}
    log-replies: {{ yesno .Server.LogReplies }}
    log-servfail: {{ yesno .Server.LogServfail }}
    log-time-ascii: yes

    # Statistics
    extended-statistics: {{ yesno .Server.ExtendedStatistics }}
    statistics-interval: 0
    statistics-cumulative: {{ yesno .Server.StatisticsCumulative }}

{{- if .Server.TLSCertBundle }}
    # TLS
    tls-cert-bundle: {{ .Server.TLSCertBundle }}
{{- end }}

{{- if .Server.RootHints }}
    # Root hints
    root-hints: {{ .Server.RootHints }}
{{- end }}

# Remote control
remote-control:
    control-enable: {{ yesno .RemoteControl.Enabled }}
    control-interface: {{ .RemoteControl.ControlInterface }}
    control-use-cert: {{ yesno .RemoteControl.ControlUseCert }}

{{- if .Dnstap.Enabled }}

# dnstap (structured binary query/response logging)
dnstap:
    dnstap-enable: yes
    dnstap-socket-path: "{{ .Dnstap.SocketPath }}"
    dnstap-send-identity: {{ yesno .Dnstap.SendIdentity }}
    dnstap-send-version: {{ yesno .Dnstap.SendVersion }}
    dnstap-log-client-query-messages: {{ yesno .Dnstap.LogClientQueryMessages }}
    dnstap-log-client-response-messages: {{ yesno .Dnstap.LogClientResponseMessages }}
    dnstap-log-resolver-query-messages: {{ yesno .Dnstap.LogResolverQueryMessages }}
    dnstap-log-resolver-response-messages: {{ yesno .Dnstap.LogResolverResponseMessages }}
{{- end }}

{{- range .ForwardZones }}

forward-zone:
    name: "{{ .Name }}"
{{- range .ForwardAddrs }}
    forward-addr: {{ . }}
{{- end }}
{{- if .ForwardFirst }}
    forward-first: yes
{{- end }}
{{- if .ForwardTLS }}
    forward-tls-upstream: yes
{{- end }}
{{- end }}

{{- range .StubZones }}

stub-zone:
    name: "{{ .Name }}"
{{- range .StubAddrs }}
    stub-addr: {{ . }}
{{- end }}
{{- if .StubPrime }}
    stub-prime: yes
{{- end }}
{{- if .StubFirst }}
    stub-first: yes
{{- end }}
{{- end }}
`

// WriteConfig renders the Unbound config and writes it atomically.
func WriteConfig(cfg *UnboundServerConfig, path string) error {
	var buf bytes.Buffer
	if err := confTemplate.Execute(&buf, cfg); err != nil {
		return fmt.Errorf("render unbound.conf: %w", err)
	}

	// Atomic write: tmp → rename
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, buf.Bytes(), 0644); err != nil {
		return fmt.Errorf("write temp config: %w", err)
	}
	if err := os.Rename(tmp, path); err != nil {
		_ = os.Remove(tmp)
		return fmt.Errorf("rename config: %w", err)
	}
	return nil
}

// RenderConfig renders the config to a string (for preview/testing).
func RenderConfig(cfg *UnboundServerConfig) (string, error) {
	var buf bytes.Buffer
	if err := confTemplate.Execute(&buf, cfg); err != nil {
		return "", fmt.Errorf("render unbound.conf: %w", err)
	}
	return buf.String(), nil
}
